stages:
  - dev

deploy-dev:
  stage: dev
  tags:
    - gcp
  script:
    - docker image prune -af
    - docker builder prune -f
    - echo "Deployment on xplor-dev server."
    - Path=$(pwd)
    - cd /home/ubuntu/script && ./env_script.sh staging $CI_PROJECT_NAME-dev $VAULT_TOKEN && cd $Path
    - mv /home/ubuntu/script/.env $Path
    - |
      sshpass -p $Xplor_Password ssh $Xplor_Username@$Xplor_IP"
        if [[ -d "$CI_PROJECT_NAME" ]]; then
          cd /home/ubuntu/$CI_PROJECT_NAME
          docker-compose down
          cd /home/ubuntu/ && sudo rm -rf $CI_PROJECT_NAME
        fi "

    - sshpass -p $Xplor_Password ssh $Xplor_Username@$Xplor_IP "git clone -b develop https://user:'$GITLAB_ACCESS_TOKEN'@gitlab.thewitslab.com/wil-workspace/xplor/'$CI_PROJECT_NAME'.git"
    - sshpass -p $Xplor_Password scp .env $Xplor_Username@$Xplor_IP:/home/ubuntu/$CI_PROJECT_NAME
    - sshpass -p $Xplor_Password ssh -tt $Xplor_Username@$Xplor_IP  "
        cd /home/ubuntu/$CI_PROJECT_NAME && docker-compose up -d --build "
    - echo "https://xplor-registry-nest-dev.thewitslab.com" 
