version: '3'
services:
  xplor_registry_backend_service:
    container_name: Xplor-registry-nest-backend
    build: .
    ports:
      - 1089:3000
    restart: always
    environment:
      - REGISTRY_SERVICE_URL=${REGISTRY_SERVICE_URL}
      - SUNBIRD_IDENTITY_SERVICE_URL=${SUNBIRD_IDENTITY_SERVICE_URL}
      - SUNBIRD_VC_SERVICE_URL=${SUNBIRD_VC_SERVICE_URL}
      - SUNBIRD_SCHEMA_SERVICE_URL=${SUNBIRD_SCHEMA_SERVICE_URL}
      - FILE_STORE_LOCAL_PATH=${FILE_STORE_LOCAL_PATH}
      - WALLET_SERVICE_URL=${WALLET_SERVICE_URL}
      - SELF_ISSUED_ORGANIZATION_NAME=${SELF_ISSUED_ORGANIZATION_NAME}
      - SELF_ISSUED_SCHEMA_TAG=${SELF_ISSUED_SCHEMA_TAG}
      - SELF_ISSUED_SCHEMA_ID=${SELF_ISSUED_SCHEMA_ID}
      - SELF_ISSUED_SCHEMA_VERSION=${SELF_ISSUED_SCHEMA_VERSION}
    networks:
      - xplor-network

networks:
  xplor-network:
    external: true
