export default () => ({
  REGISTRY_SERVICE_URL: process.env.REGISTRY_SERVICE_URL,
  SUNBIRD_IDENTITY_SERVICE_URL: process.env.SUNBIRD_IDENTITY_SERVICE_URL,
  SUNBIRD_VC_SERVICE_URL: process.env.SUNBIRD_VC_SERVICE_URL,
  SUNBIRD_SCHEMA_SERVICE_URL: process.env.SUNBIRD_SCHEMA_SERVICE_URL,
  FILE_STORE_LOCAL_PATH: process.env.FILE_STORE_LOCAL_PATH,
})
